### PR TITLE
logoff api exposed, added mock utility

### PR DESCRIPTION
**Pull request by m-terra**
Hi @ureuzy 

Another one :) I added the logoff api method and mocking utilities.

Cheers, Andy

### CODE REVIEW

**Comment by m-terra** [comment]
@ureuzy pls don't merge yet, there is something missing in the config use of the mock. thx

**Comment by ureuzy** [comment]
@m-terra Is this PR still subject to change?

**Comment by m-terra** [comment]
@ureuzy we just started integration testing and i would like to keep it open. i'm pretty sure there will be some changes

**Comment by m-terra** [comment]
@ureuzy ready to merge

btw, i added a json boolean mapper type that you could also use for the SLB part

**Review by ureuzy — APPROVED** [review]
@m-terra 

LGTM

Sorry for the delay.

**Comment by m-terra** [comment]
@ureuzy thank you :)

**Pull request merged**
