### PR TITLE
Feature/gslb subresource operators

### PR DESCRIPTION
**Pull request by m-terra**
hi @ureuzy 

In the PR I added:

- subresource access, e.g. zone/services
- package refactoring for subresources
- validation of rest argument count

cheers

### CODE REVIEW

**Review by ureuzy — COMMENTED** [review]
@m-terra 

I have one question.

Can you tell me why the package names are redundant as follows?

```
pkg/axapi/gslb/zone/zoneservice/service.go
```

I expect

```
pkg/axapi/gslb/zone/service/service.go
```

I also notice that in this case only the file name is service, not zoneserice.

Thanks again for your contributions :)

**Comment by m-terra** [comment]
@ureuzy 

that is because we would end up with multiple packages named `port` or `service`, especially when adding more resources and subresources in the future. a current example:

`gslb/serviceip/port` and `slb/virtualserver/port`

then i noticed that the main branch already has a qualified naming in https://github.com/m-terra/acos-client-go/tree/main/pkg/axapi/slb/virtualserverport so i applied the same for all packages.

**Comment by ureuzy** [comment]
@m-terra 

Understood, please give me a little more time for review.

**Comment by m-terra** [comment]
@ureuzy 

sure no hurry at all. i will also investigate why coverage decreased and fix if possible.

**Review by ureuzy — APPROVED** [review]
LGTM

**Pull request merged**
